update deploy pipeline

diff --git a/.github/workflows/CI-Pipeline-Front.yml b/.github/workflows/CI-Pipeline-Front.yml
--- a/.github/workflows/CI-Pipeline-Front.yml
+++ b/.github/workflows/CI-Pipeline-Front.yml
@@ -39,8 +39,42 @@ jobs:
     - name: Deploy
       if: github.ref == 'refs/heads/main'  
       run: |
-        curl -X POST \
+        DEPLOY_ID=$(curl -s -X POST \
           -H "Authorization: Bearer ${{ secrets.DEPLOY_API_KEY }}" \
           -H "Content-Type: application/json" \
           -d '{}' \
-          https://api.render.com/v1/services/srv-cs6igbrtq21c73dt5ot0/deploys
+          https://api.render.com/v1/services/srv-cs6igbrtq21c73dt5ot0/deploys | jq -r '.id')
+
+          echo "Backend deployment triggered with ID: $DEPLOY_ID"
+          echo "deploy_id=$DEPLOY_ID" >> $GITHUB_ENV
+
+    - name: Deploy
+      if: github.ref == 'refs/heads/main'  
+      run: |
+          for i in {1..90}; do
+            DEPLOY_STATUS=$(curl -s \
+              -H "Authorization: Bearer ${{ secrets.DEPLOY_API_KEY }}" \
+              -H "Content-Type: application/json" \
+              https://api.render.com/v1/services/srv-cs6igbrtq21c73dt5ot0/deploys/${{ env.deploy_id }} | jq -r '.status')
+
+            echo "Current deploy status: $DEPLOY_STATUS"
+
+            if [ "$DEPLOY_STATUS" == "live" ]; then
+              echo "Deployment succeeded!"
+              break
+            elif [ "$DEPLOY_STATUS" == "failed" ]; then
+              echo "Deployment failed!"
+              exit 1
+            elif [ "$DEPLOY_STATUS" == "canceled" ]; then
+              echo "Deployment was canceled!"
+              exit 1
+            fi
+
+           sleep 10
+          done
+          
+          if [ "$DEPLOY_STATUS" != "live" ]; then
+            echo "Deployment timeout or unknown state!"
+            exit 1
+          fi
+          
